### ISSUE TITLE
How do I compose a markdown using the TextEdit file on Mac, it is acting weird when I open the text edit file "resume.me.rtf" with Atom.

### ISSUE THREAD

**Issue by parthw98** [jakobzhao/geog458#1]

**Comment by kcroland** [comment]
I think you may be editing the wrong file. Markdown files should have the extension `.md` such as `resume.md`

If you don't see that file, then you could just make a new file on Atom with that extension and copy/paste the template from the lab specifications.

**Comment by jakobzhao** [comment]
Yes! You @kcroland is right. You will need to create a `resume.md` via atom, and edit your resume in atom using markdown syntax.

**Comment by jakobzhao** [comment]
@parthw98 I encourage to keep the issue open to allow other users who have the same problem can learn from this issue comments :) Thanks

**Comment by parthw98** [comment]
OK!!
