### ISSUE TITLE
Missing ICONS 

### ISSUE THREAD

**Issue by parthw98** [jakobzhao/geog458#15]
<img width="1316" alt="Screen Shot 2020-05-02 at 12 53 22 PM" src="https://user-images.githubusercontent.com/62955963/80858007-13880e00-8c74-11ea-8427-b8ef5ecae4c4.png">
After finishing the code all my icons have disappeared. Can someone please tell me where I went wrong?

**Comment by parthw98** [comment]
<img width="1289" alt="Screen Shot 2020-05-02 at 1 04 21 PM" src="https://user-images.githubusercontent.com/62955963/80858231-a8d7d200-8c75-11ea-8b29-1eb493618015.png">
This is my resulting live server.

**Comment by jakobzhao** [comment]
open inspector to track where the bugs are.

**Comment by parthw98** [comment]
I can hardly understand the codes written in the inspector. Is there another way to track bugs?

**Comment by parthw98** [comment]
https://github.com/parthw98/airportsinus/blob/master/index.html

Here is my code

**Comment by lolakang** [comment]
```
      pointToLayer: function (feature, latlng) {
        var id = 0;
        if (feature.properties.CNTL_TWR == "Y") { id = 0; }
        else { id = 1; }
        return L.marker(latlng, {icon: L.divIcon({className: 'fa fa-plane marker-color-' + (id + 1).toString() })});
```
This part should be your code for the icons. Sometimes, I just simply change the "fa" to "fas" or always go with some old version code of the icons since it always works for me.
