### ISSUE TITLE
Lab4 why it doesn't show on my link?

### ISSUE THREAD

**Issue by lolakang** [jakobzhao/geog458#16]
my web page works perfectly in my atom-live-server, but when I update to my GitHub, the page is not found. I did change my setting to master and got a link, but the link could not bring me there. Is there any way I  could fix this problem?

**Comment by lolakang** [comment]
the developer tool said : Mixed Content. However, when I change HTTP to https, it could show up even on my atom live server.

**Comment by jakobzhao** [comment]
usually, https is recommended.
