### ISSUE TITLE
Lab 4 Cannot find "Tile Server" on Browser

### ISSUE THREAD

**Issue by alexz1** [jakobzhao/geog458#17]
I have followed the instructions and installed all the plugins necessary. I am looking on the browser and cannot find the server tile. Is it under a different name on the browser? Ia m also using the desktop version 3.12.1 not sure if that helps too.

**Comment by alexz1** [comment]
Also does anyone know what the Bucket on google cloud is too?

**Comment by jakobzhao** [comment]
the tile server is named after XYZ tiles
