### ISSUE TITLE
Lab 4: Why my repository is not accessible via the url?

### ISSUE THREAD

**Issue by yihangsun** [jakobzhao/geog458#18]
When I try to look up my repository with the URL `https://[your_github_username].github.io/[your_repository_name]`, it shows 404 "File Not Found", even though I can see my repository with complete materials and even the index.html in live server.

**Comment by jakobzhao** [comment]
have you activated the Github pages?

**Comment by yihangsun** [comment]
Indeed, I didn't activate my Github page. However, after I did, I have a new problem. My webmap is not complete. There were problems saying 

> Mixed Content: The page at 'https://yihangsun.github.io/maptiles/' was loaded over HTTPS, but requested an insecure stylesheet 'http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css'. This request has been blocked; the content must be served over HTTPS.

However, I fixed the HTTP to HTTPS, it said "Name_Invalid". What should I do?

**Comment by kiku511** [comment]
I think the leaflet stylesheet that you are referencing does not exist on https. Try using the links mentioned on this webpage instead: https://cdnjs.com/libraries/leaflet

**Comment by yihangsun** [comment]
Solved! Thank you
