### ISSUE TITLE
Bootstrap Templates

### ISSUE THREAD

**Issue by Cxdrik21** [jakobzhao/geog458#2]
I was just a bit confused on how you are supposed to access the templates; Do you download the template to your repository separately, or are some of them included in the Bootstrap Startup files we downloaded?

**Comment by kcroland** [comment]
The Bootstrap files linked in the specification is one of the templates you can use. If you want a different one, you can download a different set of files from [Start Bootstrap](https://startbootstrap.com/) and put them in your repository.

Double clicking the downloaded `index.html` file in your file explorer will open it in browser and you can see what it looks like. This is the file you will edit in Atom to change the content of the page.

**Comment by Cxdrik21** [comment]
Ok cool. If you want to use this other template, should you delete the startup bootstrap files?

**Comment by jakobzhao** [comment]
@kcroland Thanks for using the issue to help the classmates. @kcroland

**Comment by kcroland** [comment]
> Ok cool. If you want to use this other template, should you delete the startup bootstrap files?

Yea you should delete the other bootstrap files
