### ISSUE TITLE
GitHub Page Conversion Issue

### ISSUE THREAD

**Issue by parthw98** [jakobzhao/geog458#3]
My Markdowns, links, and images are not available on the my website and causing issues in ATOM. Can I lease get an appointment with you in order to clear these issues or problems?

**Comment by jakobzhao** [comment]
Sure, Let us meet after Thursday's class.  But first, I encourage you to share the screenshot (codes, the preview of the screenshot) here at Issues. Then, students can also help you with the questions you have experienced. And I believe most of the questions can be solved here.

**Comment by parthw98** [comment]
<img width="1078" alt="Screen Shot 2020-04-08 at 10 39 54 PM" src="https://user-images.githubusercontent.com/62955963/78813014-0320a280-79ea-11ea-923f-bcdfcdf57d9c.png">
<img width="1623" alt="Screen Shot 2020-04-08 at 10 38 47 PM" src="https://user-images.githubusercontent.com/62955963/78813024-074cc000-79ea-11ea-92ec-b317f8742267.png">
<img width="1076" alt="Screen Shot 2020-04-08 at 10 40 26 PM" src="https://user-images.githubusercontent.com/62955963/78813027-09168380-79ea-11ea-87f7-d84260a5162f.png">

**Comment by parthw98** [comment]
I am getting this when I try opening parthw98.github.io

<img width="1078" alt="Screen Shot 2020-04-08 at 10 42 57 PM" src="https://user-images.githubusercontent.com/62955963/78813372-8b06ac80-79ea-11ea-8c5b-d6f07cbd7e83.png">

**Comment by jouho** [comment]
@parthw98
If you are wondering why your contents are not appearing in your repository home, it is because your resume contents are stored in `resume.md` and not `README.md`.  Github always shows `README.md` as an introduction to your repository. Therefore you should be able to see your resume contents if you click on `resume.md`. You could also rewrite `README.md` If you want to show your resume contents there, but to make the URL more intuitive to understand that it is a resume, I would keep it the same. Does this solve your problem?

**Comment by parthw98** [comment]
Yes!!! Thank you!

**Comment by parthw98** [comment]
<img width="1514" alt="Screen Shot 2020-04-09 at 8 56 21 PM" src="https://user-images.githubusercontent.com/62955963/78912055-c6fe4800-7aa4-11ea-9cd3-f4b67bf64be3.png">
<img width="1514" alt="Screen Shot 2020-04-09 at 8 57 14 PM" src="https://user-images.githubusercontent.com/62955963/78912083-d2517380-7aa4-11ea-96ab-ef05be2f260a.png">
Just to confirm, are these the desired outcomes?

**Comment by parthw98** [comment]
<img width="1516" alt="Screen Shot 2020-04-09 at 9 09 22 PM" src="https://user-images.githubusercontent.com/62955963/78913525-c49ced80-7aa6-11ea-9fef-1223ded8ada1.png">
ohh got it!! Thanks!

**Comment by weixingnie** [comment]
I am not sure what is the symbol "#" suppose to mean. If u are trying to use it as the header, then you probably need to check the header again.

**Comment by weixingnie** [comment]
oh, nvm. You got it. Good job!
