### ISSUE TITLE
Images not showing up in resume on github pages

### ISSUE THREAD

**Issue by gordydelap** [jakobzhao/geog458#4]
For some reason images aren't showing up in my resume if I access it through github pages:
![image](https://user-images.githubusercontent.com/24648589/78967295-eaca8980-7ab6-11ea-89ea-df7e3a86a93e.png)

However, if I open up the resume markdown file from my github repository I have no issues seeing the image:
![image](https://user-images.githubusercontent.com/24648589/78967397-367d3300-7ab7-11ea-934a-212924944728.png)

Does anyone know how to fix this?

**Comment by kiku511** [comment]
Not sure what might be going wrong there. Maybe GitHub pages does not support image URLs like that. Try using this synatax: 
![imagename](http://url.to/image.png = 250x)

**Comment by jakobzhao** [comment]
I understand that some HTML syntax still work in markdown file, markdown also has its own way to include an image. as below

`![image-title](image-url)`

**Comment by jakobzhao** [comment]
this is how I use HTML code snippet in a markdown file. Please give a try.

`<a href="https://hgis.uw.edu"><img src="assets/logo.png" align="right" width="230px" target="_blank" /></a> `

**Comment by gordydelap** [comment]
> I understand that some HTML syntax still work in markdown file, markdown also has its own way to include an image. as below
> 
> `![image-title](image-url)`

Is there a way to resize the image without using HTML?

**Comment by gordydelap** [comment]
> Not sure what might be going wrong there. Maybe GitHub pages does not support image URLs like that. Try using this synatax:
> ![imagename](http://url.to/image.png = 250x)

couldn't get this to work :(

**Comment by jakobzhao** [comment]
> > I understand that some HTML syntax still work in markdown file, markdown also has its own way to include an image. as below
> > `![image-title](image-url)`
> 
> Is there a way to resize the image without using HTML?

Unfortunately, I do not think Markdown provides the resize function.
