### ISSUE TITLE
GitHub cannot launch from CANVAS 

### ISSUE THREAD

**Issue by catharinadepari** [jakobzhao/geog458#5]
Hello everyone,

I had an issues in opening/launching my git hub from UW canvas. It worked properly when I submitted it before the due last night. Is it because I resubmitted my url a couple of times? Here is what it looks like now:

image.
![image](https://user-images.githubusercontent.com/62864836/79022338-8ea54b00-7b32-11ea-8665-2a9819dfbdad.png)

Here is what my page should look like:
![image](https://user-images.githubusercontent.com/62864836/79022376-a11f8480-7b32-11ea-8172-114f18c4ec80.png)

![image](https://user-images.githubusercontent.com/62864836/79022431-b98f9f00-7b32-11ea-9935-6408bcbde77e.png)

And for your reference, here some pull requests on my github page
image
![image](https://user-images.githubusercontent.com/62864836/79022446-c6ac8e00-7b32-11ea-9ce0-861bea557ee1.png)

It is very urgent and I really appreciate your help.
Many thanks

-Catharina-

**Comment by jakobzhao** [comment]
I will encourage you to backup all the necessary files in this repo. And then delete this repo on the GitHub. After that, recreate a new rep in the same name and insert the backupped files.

**Comment by catharinadepari** [comment]
Hello Prof Zhao, do you mean that I need to backup them in the repo in my own computer?Thank you, Prof Zhao

**Comment by catharinadepari** [comment]
Prof Zhao, I have created a new repo on GitHub with the same content and under the same name. 
Would you please suggest how I can resubmit it?

Thank you for your kind help.
