### ISSUE TITLE
Twitter Developer Account Application Rejection and Fix

### ISSUE THREAD

**Issue by weixingnie** [jakobzhao/geog458#6]
![image](https://user-images.githubusercontent.com/43578997/79644878-a008db80-8160-11ea-81fe-d324654c9973.png)

**Comment by joshuaji03** [comment]
Did you use your uw.edu email account? I was waiting for days then I replied again with my uw email and got accept immediately.

**Comment by jakobzhao** [comment]
@weixingnie As indicated by @joshuaji03, have you tried your uw email account?

**Comment by weixingnie** [comment]
I tried but it didn't work

**Comment by alexz1** [comment]
I used both of my accounts Personal and UW email and my developer account is still under review. I am not sure what to do.

**Comment by parthw98** [comment]
^Same. I have already applied with my UW email and personal email and I've still not received my conformation or approval. Its been over 4 days. What could be a solution to this?

**Comment by parthw98** [comment]
Is there an alternative option to complete lab 2?

**Comment by jouho** [comment]
I am not sure if anyone read our slack channel, but I am willing to share my Twitter keys privately for this lab purpose. Message me on slack and I will reply with my keys.

**Comment by jakobzhao** [comment]
@parthw98 there is! I will talk about it in class.
