### ISSUE TITLE
For the lab 2, how could we make our own geosearch.ipynb?

### ISSUE THREAD

**Issue by lolakang** [jakobzhao/geog458#7]
I realized that we need our own .ipynb for our own repository. There are two ways that I think I could go with. One is copy-paste on a new file with .ipynd, and the other way is downloading the edited .ipynd file from Jupyter directly. However, those two ways look different on Atom. So, which one should I choose?

**Comment by jakobzhao** [comment]
Good questions, I think you will need to make your own on Jupyter. however, the main expectation is just to crawl data based on the parameters you picked

**Comment by samc99** [comment]
How do we connect our the .ipynd to our computers so that the tweet.csv can be created by running the code. Can someone explain how .ipynd files works?

**Comment by lolakang** [comment]
> How do we connect our the .ipynd to our computers so that the tweet.csv can be created by running the code. Can someone explain how .ipynd files works?

It looks like the .ipynd should run through the Jupyter in this lab. We only need to edit the last part of the .ipynd but still need to click run for the first two parts to set up. Then, you will get your result.
