### ISSUE TITLE
For Lab 02, How do I create folders in github for "assets" and "img" in order to get the desired file structure?

### ISSUE THREAD

**Issue by parthw98** [jakobzhao/geog458#8]
<img width="1514" alt="Screen Shot 2020-04-22 at 9 23 12 PM" src="https://user-images.githubusercontent.com/62955963/80004088-8a3c4300-84df-11ea-9c29-0b348a9a1eda.png">

**Comment by jouho** [comment]
If you clone this repository, you should be able to create a folder inside the repository through your local computer. After that, simply commit and push the change you made.
![image](https://user-images.githubusercontent.com/43765840/80039947-d8d0e980-84ad-11ea-9450-ab33341e83a1.png)
